In [1]:
from gensim.models import KeyedVectors
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [2]:
word2vec_path = 'GoogleNews-vectors-negative300.bin'  # Ensure you have this file
word2vec = KeyedVectors.load_word2vec_format(word2vec_path, binary=True)

In [ ]:
dim = 300
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]
sent_length = 8

In [4]:
tokenizer = {}
index = 1
for sentence in sent:
    for word in sentence.split():
        if word not in tokenizer:
            tokenizer[word] = index
            index += 1

In [5]:
tokenizer

{'the': 1,
 'glass': 2,
 'of': 3,
 'milk': 4,
 'juice': 5,
 'cup': 6,
 'tea': 7,
 'I': 8,
 'am': 9,
 'a': 10,
 'good': 11,
 'boy': 12,
 'developer': 13,
 'understand': 14,
 'meaning': 15,
 'words': 16,
 'your': 17,
 'videos': 18,
 'are': 19}

In [6]:
embedding_matrix = np.zeros((len(tokenizer) + 1, dim))
for word, i in tokenizer.items():
    if word in word2vec:
        embedding_matrix[i] = word2vec[word]

In [13]:
print(embedding_matrix.shape)
embedding_matrix

(20, 300)


array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.08007812,  0.10498047,  0.04980469, ...,  0.00366211,
         0.04760742, -0.06884766],
       [-0.22363281,  0.12402344, -0.09130859, ..., -0.02307129,
         0.11376953, -0.33789062],
       ...,
       [ 0.19433594,  0.09960938,  0.08251953, ..., -0.17382812,
        -0.15917969,  0.1796875 ],
       [-0.04370117,  0.17089844,  0.02526855, ..., -0.26171875,
        -0.03442383,  0.00616455],
       [-0.09667969, -0.02636719,  0.09033203, ..., -0.01965332,
         0.21386719,  0.13671875]])

In [8]:
one_hot_repr = [[tokenizer[word] for word in sentence.split()] for sentence in sent]
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

In [9]:
model = Sequential()

model.add(Embedding(input_dim=len(tokenizer) + 1, output_dim=dim, weights=[embedding_matrix], trainable=False))

In [10]:
embedded_docs[0]

array([0, 0, 0, 0, 1, 2, 3, 4])

In [11]:
print(embedded_docs[0:1].shape)
embedded_docs[0:1]

(1, 8)


array([[0, 0, 0, 0, 1, 2, 3, 4]])

In [12]:
prediction = model.predict(embedded_docs[0:1])
print(prediction[0].shape)
prediction[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
(8, 300)


array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.22363281,  0.12402344, -0.09130859, ..., -0.02307129,
         0.11376953, -0.33789062],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.07324219,  0.1328125 , -0.00698853, ...,  0.23828125,
         0.09472656, -0.25390625]], dtype=float32)